### Configfile for Vascular Aging RNA pipeline####
###### 
## PERSONAL INFORMATION ##
# Author: Christian Heyer
# Position: PhD Student
# Date: 08.07.2020
# Institution: DKFZ B240

## PROJECT INFORMATION ##
# Name of the project: Vascular Aging
# Phabricator's project: #vascaging
# Assigned task (optional):


## SCRIPT INFORMATION ##
# Title: Config Script for Snakemake rnaseq pipeline for APelin experiments
# Description: Config file based off of https://github.com/snakemake-workflows/rna-seq-star-deseq2/
#   Used for the Apelin Vascular Aging experiment.
# Environments: conda env with snakemake installed
# Dependencies: python3, snakemake=>5.1
# Usage: use with `snakemake --configfile {this_file}

######

# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: ./data/TerfKO_samples.tsv
counts: ./data/TerfKO_counts.tsv
# path or URL to sequencing unit sheet (TSV format, columns: sample, unit, fq1, fq2, 
# strandedness). Units are technical replicates (e.g. lanes, or resequencing of the 
# same biological sample).If the column "strandedness" is present (which is optional), 
# can be empty or has one of these values: none, yes or reverse. none is for unstranded 
# protocols, yes an reverse follow the nomenclature used in `htseq-count --reverse` 
# which is referenced in STAR manual section 7, "Counting number of reads per gene".

gene_name_type: ENSEMBL
organism: "Mus musculus"


### Data Dirs ###
dirs:
  BASE_DATA_DIR: ''
  BASE_ANALYSIS_DIR: 'data/TerfKO/'

perform_perturbation: False



pca:
  labels:
    # columns of sample sheet to use for PCA
    - condition

diffexp:
  gsea_use_stat: True
  pval_threshold: 0.05
  LFC_threshold: 0.5 
  shrink_lfc: True
  # contrasts for the deseq2 results method
  contrasts:
    condition:  
      basal_pos_vs_bas_neg:
        - basal_cre_positive
        - basal_cre_negative
  model: "~condition"
  filter_samples:
    condition: False 

gsea:
  Hallmark_gsea:
    category: H
    subcategory: NULL
    use_gsea: True
    database: MSigDB
    id_class: ENSEMBL
comp_groups:
  condition:    
    basal_pos_vs_bas_neg:
      - basal_cre_positive
      - basal_cre_negative
  
params:
  star: ""
  cutadapt-se: ""
  cutadapt-pe: ""

group_colors:
  condition:
    basal_cre_positive: "red"
    basal_cre_negative: "blue"

do_salmon: False
run_mitch: False
run_carnival:
  vanilla: False
  inverse: False
  sample: False
  joint_rep: False
run_kallisto: False
run_qc: False

cplex_solver: ""

DKFZ: FALSE
